// Code generated by ogen, DO NOT EDIT.

package orderV1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements cancelOrder operation.
//
// Отменяет заказ, если он ещё не оплачен: статус
// PENDING_PAYMENT меняется на CANCELLED. Заказ в статусе PAID
// отменить нельзя.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements createOrder operation.
//
// Создаёт новый заказ на основе списка деталей,
// выбранных пользователем. Сервис получает детали
// через InventoryService.ListParts, проверяет, что все переданные
// part_uuids существуют, считает total_price и сохраняет заказ со
// статусом PENDING_PAYMENT.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByUuid implements getOrderByUuid operation.
//
// Возвращает полную информацию о заказе по его
// идентификатору.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (r GetOrderByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements payOrder operation.
//
// Проводит оплату ранее созданного заказа. Сервис
// вызывает PaymentService.PayOrder, передавая user_uuid, order_uuid и
// payment_method, получает transaction_uuid и переводит заказ в статус
// PAID.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}
