// Code generated by ogen, DO NOT EDIT.
package orderV1

type CancelOrderRes interface {
	cancelOrderRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type GetOrderByUuidRes interface {
	getOrderByUuidRes()
}

type PayOrderRes interface {
	payOrderRes()
}
