// Code generated by ogen, DO NOT EDIT.

package orderV1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements cancelOrder operation.
	//
	// Отменяет заказ, если он ещё не оплачен: статус
	// PENDING_PAYMENT меняется на CANCELLED. Заказ в статусе PAID
	// отменить нельзя.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements createOrder operation.
	//
	// Создаёт новый заказ на основе списка деталей,
	// выбранных пользователем. Сервис получает детали
	// через InventoryService.ListParts, проверяет, что все переданные
	// part_uuids существуют, считает total_price и сохраняет заказ со
	// статусом PENDING_PAYMENT.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrderByUuid implements getOrderByUuid operation.
	//
	// Возвращает полную информацию о заказе по его
	// идентификатору.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (GetOrderByUuidRes, error)
	// PayOrder implements payOrder operation.
	//
	// Проводит оплату ранее созданного заказа. Сервис
	// вызывает PaymentService.PayOrder, передавая user_uuid, order_uuid и
	// payment_method, получает transaction_uuid и переводит заказ в статус
	// PAID.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
