// Code generated by mockery. DO NOT EDIT.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/massodo1993/service-example/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, orderUuid, userUuid, pm
func (_m *PaymentClient) PayOrder(ctx context.Context, orderUuid uuid.UUID, userUuid uuid.UUID, pm model.PaymentMethod) (uuid.UUID, error) {
	ret := _m.Called(ctx, orderUuid, userUuid, pm)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) (uuid.UUID, error)); ok {
		return rf(ctx, orderUuid, userUuid, pm)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) uuid.UUID); ok {
		r0 = rf(ctx, orderUuid, userUuid, pm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUuid, userUuid, pm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUuid uuid.UUID
//   - userUuid uuid.UUID
//   - pm model.PaymentMethod
func (_e *PaymentClient_Expecter) PayOrder(ctx interface{}, orderUuid interface{}, userUuid interface{}, pm interface{}) *PaymentClient_PayOrder_Call {
	return &PaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUuid, userUuid, pm)}
}

func (_c *PaymentClient_PayOrder_Call) Run(run func(ctx context.Context, orderUuid uuid.UUID, userUuid uuid.UUID, pm model.PaymentMethod)) *PaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.PaymentMethod))
	})
	return _c
}

func (_c *PaymentClient_PayOrder_Call) Return(_a0 uuid.UUID, _a1 error) *PaymentClient_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentClient_PayOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) (uuid.UUID, error)) *PaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
